name: Flutter Workflow

on: [push, workflow_dispatch]
env:
  # 使用しているFlutter SDKのバージョン
  flutter_version: 3.13.5
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Flutterの環境構築(cacheが存在すればそれを使用する)
      - name: Create Flutter Environment
        uses: subosito/flutter-action@v2.11.0
        with:
          flutter-version: ${{ env.flutter_version }}
          cache: true
          cache-key: flutter_environment-${{ runner.os }}-${{ env.flutter_version }}
          channel: 'stable'

      - run: flutter doctor -v

      - run: flutter doctor --android-licenses

      - run: java --version

      - run: flutter --scan build apk

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit tests
        run: flutter test --coverage

#      - name: Upload to code coverage
#        uses: codecov/codecov-action@v1.2.2
#        with:
#          token: ${{secrets.CODECOV_TOKEN}}
#          file: coverage/lcov.info

      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v1
        with:
          api-level: 29
          script: flutter drive --driver=test_driver/main_test.dart --target integration_test/app_test.dart

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: Upload Screenshoots
        uses: actions/upload-artifact@v3
        with:
          name: Test result screenshots
          path: screenshots/*.png