name: Check and test the source code
on:
  pull_request:
    branches:
      - main
jobs:
  analysis_code:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Flutter Environment
        uses: subosito/flutter-action@v2.11.0
        with:
          flutter-version: '3.13.5'
      - name: Install packages
        run: flutter pub get
      - name: Linter
        run: flutter analyze
  test_code:
    name: Test the source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Flutter Environment
        uses: subosito/flutter-action@v2.11.0
        with:
          flutter-version: '3.13.5'
      - name: Install packages
        run: flutter pub get
      - name: Test
        run: flutter test --coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
